### PR TITLE
Fix multiple extensions

### PR DESCRIPTION
**Pull request by darklight365**
Fix to allow Android to select multiple file extensions

### CODE REVIEW

**Comment by farfromrefug** [comment]
@darklight365 thanks the fix was already done and released

**Comment by darklight365** [comment]
@farfromrefug - Am I missing something?  The most recent release in npm is version 1.1.13 which still has the bug.

**Comment by farfromrefug** [comment]
@darklight365 indeed something went wrong. let me fix that

**Comment by farfromrefug** [comment]
@darklight365 should all be good to go now. THanks for your PR!

**Pull request closed without merging**
